= Persistent vectors for Scheme

‘Persistent’ vectors are also called ‘immutable’ vectors. They are
single dimensional arrays whose past states effectively persist, as
long as some part of the program is referring to those states. They
also may be used as stacks. They can serve as a limited alternative to
lists. They have the frequent advantage that ‘pushing’ extends them at
the tail end—unlike persistent lists or
vlists,footnote:[https://lampwww.epfl.ch/papers/techlists.pdf] which
get extended at the head. However, I do not implement pushing or
popping from the head end (it is not an ideque), and I do not
implement insertion or deletion.footnote:[The vectors currently are
implemented as ‘bit-partitioned vector tries with tails’. The
implementation is a rewrite as portable Scheme of a CHICKEN egg I
wrote several years ago. That, in turn, was adapted from a generic C
macro implementation I wrote years earlier, and which was used to make
Guile 2.0 persistent vectors.]

This distribution assumes you have both GNU Make and either GNU M4 or
OpenBSD M4. For installation, you will likely want ‘doas’, ‘sudo’, or
some similar way to execute a command with superuser privileges.
However, of course, feel free to modify the GNUmakefile or not use it
at all. One can use a text editor or Awk instead of M4, for instance.

* There is installation for Chez Scheme, Gauche Scheme, CHICKEN 5, and
CHICKEN 6, which I will document. You may need chez-srfi, CHICKEN
eggs, etc.footnote:[The code is primarily for R⁷RS, with R⁶RS support
to the degree Scheme code of any variety can be tolerated by it. In
particular, I export partial implementation of SRFI-42, but find that
SRFI-42 ‘index’ variables are unreliable in at least Chez Scheme. This
is so, even though I include my own copy of the reference
implementation (mainly because too many other SRFI-42 libraries have
their ability to be extended broken). Only for Chibi and CHICKEN do I
use what ‘comes with’ the compiler/interpreter. However, ‘index’
variables are redundant with ‘:parallel’ constructs, and are a nasty
complexity, so were it up to me they would have been removed from
SRFI-42. Just do not use them. I implement them merely because one is
supposed to.]

* There is testing for the above, and also for Chibi Scheme, Loko Scheme
(both R⁶RS and R⁷RS), and Sagittarius Scheme (both R⁶RS and R⁷RS). I
will document this. I will write more tests.

== Programming interface footnote:[Indices are zero-based.]

=== Constructors

*(pvec)*:: Make an empty persistent vector.
*(pvec _elem1_ ...)*:: Make a persistent vector containing the given
     elements.
*(list*+->+*pvec _list_)*:: Make a persistent vector from the elements
     of the given list.
*(vector*+->+*pvec _vector_)*:: Make a persistent vector from the
     elements of the given vector.
*(vector*+->+*pvec _vector_ _start_)*:: Make a persistent vector from
     the elements of the given vector, starting at index _start_ and
     going to the end of the vector.
*(vector*+->+*pvec _vector_ _start_ _end_)*:: Make a persistent vector
     from the elements of the given vector, starting at index _start_
     and going to index _end{nbsp}−{nbsp}1_.
*(generator*+->+*pvec _generator_)*:: Make a persistent vector from
     the elements returned by a SRFI-158-style generator.
*(generator*+->+*pvec _generator_ _k_)*:: Make a persistent vector
     from the elements returned by at most the first _k_ elements
     returned by a SRFI-158-style generator. (Thus the generator may
     be an infinite generator.)

=== Reverse constructors

*(pvec*+->+*list _pvec_)*:: Make a list from the elements of the given
     persistent vector.
*(pvec*+->+*list _pvec_ _start_)*:: Make a list from the elements of
     the given persistent vector, starting at index _start_ and going
     to the end of the vector.
*(pvec*+->+*list _pvec_ _start_ _end_)*:: Make a list from the
     elements of the given vector, starting at index _start_ and going
     to index _end{nbsp}−{nbsp}1_.
*(pvec*+->+*vector _pvec_)*:: Make a vector from the elements of the
     given persistent vector.
*(pvec*+->+*vector _pvec_ _start_)*:: Make a vector from the elements
     of the given persistent vector, starting at index _start_ and
     going to the end of the vector.
*(pvec*+->+*vector _pvec_ _start_ _end_)*:: Make a vector from the
     elements of the given vector, starting at index _start_ and going
     to index _end{nbsp}−{nbsp}1_.
*(pvec*+->+*generator _pvec_)*:: Make a generator from the elements of
     the given persistent vector.
*(pvec*+->+*generator _pvec_ _start_)*:: Make a generator from the
     elements of the given persistent vector, starting at index
     _start_ and going to the end of the vector.
*(pvec*+->+*generator _pvec_ _start_ _end_)*:: Make a generator from
     the elements of the given vector, starting at index _start_ and
     going to index _end{nbsp}−{nbsp}1_.

=== Type predicate

*(pvec? _object_)*:: Is _object_ a _pvec_ persistent vector? *#t* or
     *#f*

=== Structure properties

*(pvec-length _pvec_)*:: Return the number of elements in the
     persistent vector.

=== Vector operations

*(pvec-ref _pvec_ _i_)*:: Return the __i__ th element of the
     persistent vector.
*(pvec-set _pvec_ _i_ _x_)*:: Return a new persistent vector whose
     elements are the same as those of _pvec_, except that the
     __i__ th element has the value{nbsp}__x__. The new vector may
     share structure with _pvec_.
*(pvec-refs _pvec_)*:: Return multiple elements at once, possibly
     traversing the structure less frequently than if you used other
     methods. This is exactly the same procedure as *(pvec*+->+*vector
     _pvec_)*. See <<Reverse constructors>>.
*(pvec-refs _pvec_ _start_)*:: Return multiple elements at once,
     possibly traversing the structure less frequently than if you
     used other methods. This is exactly the same procedure as
     *(pvec*+->+*vector _pvec_ _start_)*. See <<Reverse
     constructors>>.
*(pvec-refs _pvec_ _start_ _end_)*:: Return multiple elements at once,
     possibly traversing the structure less frequently than if you
     used other methods. This is exactly the same procedure as
     *(pvec*+->+*vector _pvec_ _start_ _end_)*. See <<Reverse
     constructors>>.
*(pvec-sets _pvec_ _i_ _x_)*:: Return a new persistent vector whose
     elements are the same as those of _pvec_, except that the
     __i__ th and following elements have the values of the elements
     of the ordinary vector{nbsp}__x__. The new persistent vector may
     share structure with _pvec_. This method of setting elements
     might traverse structure less than other methods do.
*(pvec-sets _pvec_ _i_ _x_ _start_)*:: Return a new persistent vector
     whose elements are the same as those of _pvec_, except that the
     __i__ th and following elements have the values of some elements
     of the ordinary vector{nbsp}__x__. Only elements of _x_ from
     _start_ to the end of _x_ are used. The new persistent vector may
     share structure with _pvec_. This method of setting elements
     might traverse structure less than other methods do.
*(pvec-sets _pvec_ _i_ _x_ _start_ _end_)*:: Return a new persistent
     vector whose elements are the same as those of _pvec_, except
     that the __i__ th and following elements have the values of some
     elements of the ordinary vector{nbsp}__x__. Only elements of _x_
     from the indices _start_ to _end{nbsp}−{nbsp}1_ are used. The new
     persistent vector may share structure with _pvec_. This method of
     setting elements might traverse structure less than other
     methods do.
