= Persistent vectors for Scheme

‘Persistent’ vectors are also called ‘immutable’ vectors. They are
single dimensional arrays whose past states effectively persist, as
long as some part of the program is referring to those states. They
also may be used as stacks. They can serve as a limited alternative to
lists. They have the frequent advantage that ‘pushing’ extends them at
the tail end—unlike persistent lists or
vlists,footnote:[https://lampwww.epfl.ch/papers/techlists.pdf] which
get extended at the head. However, I do not implement pushing or
popping from the head end (it is not an ideque), and I do not
implement insertion or deletion.footnote:[The vectors currently are
implemented as ‘bit-partitioned vector tries with tails’. The
implementation is a rewrite as portable Scheme of a CHICKEN egg I
wrote several years ago. That, in turn, was adapted from a generic C
macro implementation I wrote years earlier, and which was used to make
persistent vectors for Guile 2.0.]

This distribution assumes you have both GNU Make and either GNU M4 or
OpenBSD M4. For installation, you will likely want ‘doas’, ‘sudo’, or
some similar way to execute a command with superuser privileges.
However, of course, feel free to modify the GNUmakefile or not use it
at all. One can use a text editor or Awk instead of M4, for instance.

You may have to install
chez-srfi,footnote:chez-srfi[https://github.com/arcfide/chez-srfi]
CHICKEN eggs, etc.footnote:[The code is primarily for R⁷RS, with R⁶RS
support to the degree Scheme code of any variety can be tolerated
by it. In particular, I export partial implementation of SRFI-42, but
find that SRFI-42 ‘index’ variables are unreliable in at least Chez
Scheme. This is so, even though I include my own copy of the reference
implementation (mainly because too many other SRFI-42 libraries have
their ability to be extended broken). Only for Chibi and CHICKEN do I
use what ‘comes with’ the compiler/interpreter. However, ‘index’
variables are redundant with ‘:parallel’ constructs, and are a nasty
complexity, so were it up to me they would have been removed from
SRFI-42. Just do not use them. I implement them merely because one is
supposed to.]

== Installation

Currently there are GNUmakefile installation targets for Chez Scheme,
Gauche Scheme, CHICKEN 5, and CHICKEN 6.

* To install for Chez Scheme, edit the GNUmakefile to set
  _CHEZSCHEME_INSTALLDIR_ and _CHEZ_SUDO_ as needed. Then run *make
  install-chez*{nbsp}. You can uninstall by running *make
  uninstall-chez*{nbsp}.

* To install for Gauche Scheme, edit the GNUmakefile to set
  _GAUCHE_INSTALLDIR_ and _GAUCHE_SUDO_ as needed. Then run *make
  install-gauche*{nbsp}. You can uninstall by running *make
  uninstall-gauche*{nbsp}.

* To install an egg for CHICKEN 5 or CHICKEN 6, edit the GNUmakefile
  to set _CHICKEN_5_SUDO_, _CHICKEN_6_SUDO_, and the CHICKEN tools as
  needed. Then run *make install-chicken-5-egg* or *make
  install-chicken-6-egg*{nbsp}. You can uninstall the egg by running
  *make uninstall-chicken-5-egg* or
  *make-uninstall-chicken-6-egg*{nbsp}. There are also targets to make
  source tarballs of the CHICKEN eggs.

== Testing

There is regression testing for several Scheme implementations. The
GNUmakefile targets are *check-chez-r6rs*, *check-chibi-r7rs*,
*check-gauche-r7rs*, *check-loko-r6rs*, *check-loko-r7rs*,
*check-sagittarius-r6rs*, *check-sagittarius-r7rs*,
*check-chicken-5-r7rs*, and *check-chicken-6-r7rs*{nbsp}. There is
also a *check-all-scheme-implementations* target that can be run as a
parallel make job, and which is the default target for the
GNUmakefile.

== Programming interface footnote:[Indices are zero-based.]

=== Library *(pvec)*

==== Constructors

*(pvec)*:: Make an empty persistent vector.
*(pvec _elem1_ ...)*:: Make a persistent vector containing the given
     elements.
*(list*+->+*pvec _list_)*:: Make a persistent vector from the elements
     of the given list.
*(vector*+->+*pvec _vector_)*:: Make a persistent vector from the
     elements of the given vector.
*(vector*+->+*pvec _vector_ _start_)*:: Make a persistent vector from
     the elements of the given vector, starting at index _start_ and
     going to the end of the vector.
*(vector*+->+*pvec _vector_ _start_ _end_)*:: Make a persistent vector
     from the elements of the given vector, starting at index _start_
     and going to index _end{nbsp}−{nbsp}1_.
*(generator*+->+*pvec _generator_)*:: Make a persistent vector from
     the elements returned by a
     SRFI-158-style footnote:srfi-158[https://srfi.schemers.org/srfi-158/]
     generator.
*(generator*+->+*pvec _generator_ _k_)*:: Make a persistent vector
     from the elements returned by at most the first _k_ elements
     returned by a SRFI-158-style footnote:srfi-158[] generator. (Thus
     the generator may be an infinite generator.)

==== Reverse constructors

*(pvec*+->+*list _pv_)*:: Make a list from the elements of the given
     persistent vector.
*(pvec*+->+*list _pv_ _start_)*:: Make a list from the elements of
     the given persistent vector, starting at index _start_ and going
     to the end of the vector.
*(pvec*+->+*list _pv_ _start_ _end_)*:: Make a list from the
     elements of the given vector, starting at index _start_ and going
     to index _end{nbsp}−{nbsp}1_.
*(pvec*+->+*vector _pv_)*:: Make a vector from the elements of the
     given persistent vector.
*(pvec*+->+*vector _pv_ _start_)*:: Make a vector from the elements
     of the given persistent vector, starting at index _start_ and
     going to the end of the vector.
*(pvec*+->+*vector _pv_ _start_ _end_)*:: Make a vector from the
     elements of the given vector, starting at index _start_ and going
     to index _end{nbsp}−{nbsp}1_.
*(pvec*+->+*generator _pv_)*:: Make a generator from the elements of
     the given persistent vector.
*(pvec*+->+*generator _pv_ _start_)*:: Make a generator from the
     elements of the given persistent vector, starting at index
     _start_ and going to the end of the vector.
*(pvec*+->+*generator _pv_ _start_ _end_)*:: Make a generator from
     the elements of the given vector, starting at index _start_ and
     going to index _end{nbsp}−{nbsp}1_.

==== Type predicate

*(pvec? _object_)*:: Is _object_ a _pvec_ persistent vector? *#t* or
     *#f*

==== Structure properties

*(pvec-length _pv_)*:: Return the number of elements in the
     persistent vector.

==== Vector operations

*(pvec-ref _pv_ _i_)*:: Return the __i__ th element of the
     persistent vector.
*(pvec-set _pv_ _i_ _x_)*:: Return a new persistent vector whose
     elements are the same as those of _pv_, except that the
     __i__ th element has the value{nbsp}__x__. The new vector may
     share structure with _pv_.
*(pvec-refs _pv_)*:: Return multiple elements at once, possibly
     traversing the structure less frequently than if you used other
     methods. This is exactly the same procedure as *(pvec*+->+*vector
     _pv_)*. See <<Reverse constructors>>.
*(pvec-refs _pv_ _start_)*:: Return multiple elements at once,
     possibly traversing the structure less frequently than if you
     used other methods. This is exactly the same procedure as
     *(pvec*+->+*vector _pv_ _start_)*. See <<Reverse
     constructors>>.
*(pvec-refs _pv_ _start_ _end_)*:: Return multiple elements at once,
     possibly traversing the structure less frequently than if you
     used other methods. This is exactly the same procedure as
     *(pvec*+->+*vector _pv_ _start_ _end_)*. See <<Reverse
     constructors>>.
*(pvec-sets _pv_ _i_ _x_)*:: Return a new persistent vector whose
     elements are the same as those of _pv_, except that the
     __i__ th and following elements have the values of the elements
     of the ordinary vector{nbsp}__x__. The new persistent vector may
     share structure with _pv_. This method of setting elements
     might traverse structure less than other methods do.
*(pvec-sets _pv_ _i_ _x_ _start_)*:: Return a new persistent vector
     whose elements are the same as those of _pv_, except that the
     __i__ th and following elements have the values of some elements
     of the ordinary vector{nbsp}__x__. Only elements of _x_ from
     _start_ to the end of _x_ are used. The new persistent vector may
     share structure with _pv_. This method of setting elements
     might traverse structure less than other methods do.
*(pvec-sets _pv_ _i_ _x_ _start_ _end_)*:: Return a new persistent
     vector whose elements are the same as those of _pv_, except
     that the __i__ th and following elements have the values of some
     elements of the ordinary vector{nbsp}__x__. Only elements of _x_
     from the indices _start_ to _end{nbsp}−{nbsp}1_ are used. The new
     persistent vector may share structure with _pv_. This method of
     setting elements might traverse structure less than other
     methods do.

==== Stack operations

*(pvec-push _pv_)*:: Return a persistent vector that has the same
     elements as _pv_. It may, in fact, be the same vector, though
     is not necessarily so.
*(pvec-push _pv_ _x_)*:: Return a new persistent vector whose
     elements are the same as those of _pv_, except that the new
     element _x_ is pushed onto the tail. The new persistent vector
     may share structure with _pv_.
*(pvec-push _pv_ _x1_ ... _xN_)*:: Return a new persistent vector
     whose elements are the same as those of _pv_, except that the
     new elements __x1__{nbsp}...{nbsp}__xN__ are pushed onto the
     tail. The new persistent vector may share structure with _pv_.
*(pvec-pushes _pv_ _list_)*:: Return a new persistent vector whose
     elements are the same as those of _pv_, except that the elements
     of _list_ are pushed onto the tail. The new persistent vector may
     share structure with _pv_.
*(pvec-pushes _pv_ _vector_)*:: Return a new persistent vector whose
     elements are the same as those of _pv_, except that the elements
     of _vector_ are pushed onto the tail. The new persistent vector
     may share structure with _pv_.
*(pvec-pushes _pv_ _vector_ _start_)*:: Return a new persistent vector
     whose elements are the same as those of _pv_, except that the
     elements of _vector_ beginning at index _start_ are pushed onto
     the tail. The new persistent vector may share structure with
     _pv_.
*(pvec-pushes _pv_ _vector_ _start_ _end_)*:: Return a new persistent
     vector whose elements are the same as those of _pv_, except that
     the elements of _vector_ from _start_ to _end{nbsp}−{nbsp}1_ are
     pushed onto the tail. The new persistent vector may share
     structure with _pv_.
*(pvec-pushes _pv_ _generator_)*:: Return a new persistent vector
     whose elements are the same as those of _pv_, except that the
     elements returned by a SRFI-158-style footnote:srfi-158[]
     generator are pushed onto the tail. The new persistent vector may
     share structure with _pv_.
*(pvec-pushes _pv_ _generator_ _k_)*:: Return a new persistent vector
     whose elements are the same as those of _pv_, except that the
     elements returned by a SRFI-158-style footnote:srfi-158[]
     generator are pushed onto the tail. At most the first _k_
     elements of the generator are used. (Therefore the generator may
     be infinite.) The new persistent vector may share structure with
     _pv_.
*(pvec-pop _pv_)*:: Return a new persistent vector whose elements are
     the same as those of _pv_, except the last element is removed.
     The new vector may share structure with _pv_.
*(pvec-pop _pv_ 0)*:: Return a persistent vector that has the same
     elements as _pv_. It may, in fact, be the same vector, though is
     not necessarily so.
*(pvec-pop _pv_ _n_)*:: Return a new persistent vector whose elements
     are the same as those of _pv_, except the _n_ last elements are
     removed. The new vector may share structure with _pv_.

==== Folds

*(pvec-fold _kons_ _knil_ _pv_)*:: Semantically equivalent to
     _(kons{nbsp}eₙ{nbsp}...{nbsp}(kons{nbsp}e₂{nbsp}(kons{nbsp}e₁{nbsp}knil) ){nbsp}...{nbsp})_
     where _e₁_, _e₂_, ... , _eₙ_ are the elements of the persistent
     vector{nbsp}__pv__.
*(pvec-fold _kons_ _knil_ _pv1_ ... _pvN_)*:: This is similar to
     *pvec-fold* for one persistent vector, except _kons_ is called
     with _N{nbsp}+{nbsp}1_ arguments (to account for the _N_
     persistent vectors) instead of two arguments.
*(pvec-fold-right _kons_ _knil_ _pv_)*:: Semantically equivalent to
     _(kons{nbsp}e₁{nbsp}(kons{nbsp}e₂{nbsp}...{nbsp}(kons{nbsp}eₙ{nbsp}knil) ) )_
     where _e₁_, _e₂_, ... , _eₙ_ are the elements of the persistent
     vector{nbsp}__pv__.
*(pvec-fold-right _kons_ _knil_ _pv1_ ... _pvN_)*:: This is similar to
     *pvec-fold-right* for one persistent vector, except _kons_ is
     called with _N{nbsp}+{nbsp}1_ arguments (to account for the _N_
     persistent vectors) instead of two arguments.

=== Library *(pvec eager-comprehensions)*

==== Comprehensions

Comprehensions documented in SRFI-42: footnote:srfi-42[https://srfi.schemers.org/srfi-42/] ::
*do-ec* *list-ec* *append-ec* *string-ec* *string-append-ec*
*vector-ec* *vector-of-length-ec* *sum-ec* *product-ec* *min-ec*
*max-ec* *any?-ec* *every?-ec* *first-ec* *last-ec* *fold-ec*
*fold3-ec*

*(pvec-ec _<qualifier>pass:[*]_ _<expression>_)*:: Return the
     persistent vector of all values of _<expression>_.

==== Generators

Generators documented in SRFI-42: footnote:srfi-42[] :: *:list*
*:string* *:vector* *:integers* *:range* *:real-range* *:char-range*
*:port* *:do* *:let* *:parallel* *:while* *:until*

*(:pvec _<vars>_ _<arg1>_ _<arg>pass:[*]_)*:: Run through one or more
     persistent vector, much as the *:list*, *:string*, or *:vector*
     generator does with its respective data structure.

*(:generator _<vars>_ _<arg1>_ _<arg>pass:[*]_)*:: Run through one or
     more SRFI-158-style footnote:srfi-158[] generator, in
     sequence.footnote:[With *:generator*, there is no need for
     SRFI-42’s implementationally obsolescent dispatched generators.]
